# application-dev.yml

server:
  port: 9060
spring:
  datasource:
    password: agenda
    url: jdbc:postgresql://localhost:5432/agenda
    username: agenda
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
file:
  upload-dir: ./uploads

