# application-dev.yml

server:
  port: 9060

spring:
  datasource:
    password: agenda
    url: jdbc:postgresql://localhost:5432/agenda
    username: agenda
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
