name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Adjust the branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Save data to environment file
        run: echo "DATA_KEY=your-data-value" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/theagenda_backend:${{ github.sha }} .
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/theagenda_backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/theagenda_backend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/theagenda_backend:latest

      - name: Read saved data from environment
        run:
          echo "Saved data: $DATA_KEY"
